### ISSUE TITLE
Mapping file should support external mapping files

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.aggregator.oai-pmh-repo-handler#18]
**Original report on BitBucket by Toni Sissala (GitHub: [toni-sissala](https://github.com/toni-sissala)).**

----------------------------------------

The mapping file that defines arbitrary OAI-sets, should support external mapping files. This could be achieved by adding a path-key to second-level node definitions. If a path-key is defined, its value should be a filepath that leads to the second-level node definition.

Primary mapping file:

```
    spec: 'thematic'
    name: 'Thematic'
    description: 'Thematic grouping of records'
    nodes:
      - path: '/path/to/mapping.yaml'
      - spec: 'humanities'
        name: 'Humanities'
        description: 'Studies in humanities'
        identifiers:
        - id_2
        - id_3
        - id_4
```

Secondary mapping file at /path/to/mapping.yaml

```
  - spec: 'social_sciences'
    name: 'Social sciences'
    description: 'Studies in social sciences'
    identifiers:
    - id_1
    - id_2
```

Every second-level node must either define its set in primary mapping file, or define a path-key that points to a secondary mapping file. The secondary mapping file will not support external mapping files. In other words, a secondary mapping file cannot point to a path. Previously mentioned restrictions regarding keys and values apply \(in README.md\).
